name = "RWPublicJuliaRegistry"
uuid = "84f33253-0491-444a-bf7b-6508e99dde09"
repo = "https://github.com/RoyCCWang/RWPublicJuliaRegistry"
description = "Roy Wang's Julia packages"

[packages]
2033bc0d-f107-4f18-8621-02511e8703c9 = { name = "VisualizationBag", path = "V/VisualizationBag" }
2c6f6ba7-1a3c-4d31-8511-d336c09a6ae6 = { name = "NMRSpecifyRegions", path = "N/NMRSpecifyRegions" }
2d66d368-6024-4447-9e1b-2d73b7881971 = { name = "SpatialTrees", path = "S/SpatialTrees" }
34309dff-104f-407b-ac3a-9212882a146c = { name = "PatchWorkKriging", path = "P/PatchWorkKriging" }
3aa925f2-72f3-45fa-9558-7758dda5fa92 = { name = "ITPRootFinder", path = "I/ITPRootFinder" }
5a515ddf-a3f2-4a7d-82cc-71ac3f3f244b = { name = "NMRSignalSimulator", path = "N/NMRSignalSimulator" }
a9bd3fed-5c2a-40f0-8692-fcfc96913d85 = { name = "MakiePlots", path = "M/MakiePlots" }
b41d7b93-16fb-427a-b53b-75fbbf0d305b = { name = "LazyGPR", path = "L/LazyGPR" }
bbef0899-e1b9-4221-b844-2c76cd80d375 = { name = "RieszDSP", path = "R/RieszDSP" }
c106db08-dda1-4489-a87d-67900c2fbde0 = { name = "SpatialGSP", path = "S/SpatialGSP" }
c1998724-06c8-4b73-8944-aed6cfa5d6a5 = { name = "PointSetVisualizer", path = "P/PointSetVisualizer" }
cea239a1-aef7-4735-a0ad-35c493ad27cc = { name = "CubicBSplineInterpolation", path = "C/CubicBSplineInterpolation" }
d73005cc-2eb2-45b3-9785-29d07aec07ac = { name = "NMRHamiltonian", path = "N/NMRHamiltonian" }
da5e2df6-2169-4d6c-a246-0eaf9ec197ca = { name = "RKHSRegularization", path = "R/RKHSRegularization" }
e2ef96b1-cd92-47cb-be8e-5a4a57bdd46d = { name = "ShepardsInterpolations", path = "S/ShepardsInterpolations" }
ebb73dff-5abd-42b1-a10e-869024f50034 = { name = "NMRDataSetup", path = "N/NMRDataSetup" }
f5da544b-7410-4471-9261-cf25b1dcdf05 = { name = "MaternRegression", path = "M/MaternRegression" }
f8439c9b-f421-4171-88a6-2fea72ebf919 = { name = "SingleLinkagePartitions", path = "S/SingleLinkagePartitions" }
