name = "RWPublicJuliaRegistry"
uuid = "84f33253-0491-444a-bf7b-6508e99dde09"
repo = "https://github.com/RoyCCWang/RWPublicJuliaRegistry"
description = "Roy Wang's Julia packages"

[packages]
2033bc0d-f107-4f18-8621-02511e8703c9 = { name = "VisualizationBag", path = "V/VisualizationBag" }
a9bd3fed-5c2a-40f0-8692-fcfc96913d85 = { name = "MakiePlots", path = "M/MakiePlots" }
